language: go

before_install:
  - go get github.com/jawher/mow.cli
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
go:
  - "1.15.5"